### ISSUE TITLE
bootstrap: couldn't find path: $path, true

### ISSUE THREAD

**Issue by JanStevens** [torba-rb/torba#28]
```ruby
rake torba:pack
/app/vendor/assets/torba/cache/bootstrap-sass-ac6b4156/assets/stylesheets/$path, true
Couldn't find an asset with path '/app/vendor/assets/torba/cache/bootstrap-sass-ac6b4156/assets/stylesheets/$path, true'.
Make sure that you've imported all image/font assets mentioned in a stylesheet(-s).
```

Using following Torbafile

```ruby
npm package: 'bootstrap-sass', version: '3.3.6',
  import: %w(assets/fonts/bootstrap/ assets/javascripts/bootstrap.js assets/stylesheets/)
```

I guess this has to do with the `$path` references here (`_bootstrap-compass`):

```scss
@function twbs-font-path($path) {
  @return font-url($path, true);
}

@function twbs-image-path($path) {
  @return image-url($path, true);
}

$bootstrap-sass-asset-helper: true;
```
